#
# Module manifest for module 'pwsh-clouddrives'
#
# Generated by: Tim Small
#
# Generated on: 2021-01-11
#

@{

    RootModule         = "pwsh-clouddrives.psm1"
    ModuleVersion      = "2021.01.00"
    # CompatiblePSEditions = @()
    GUID               = "fde345ce-6130-48ed-9e65-1f7a719acc60"
    Author             = "Tim Small"
    CompanyName        = "Smalls.Online"
    Copyright          = "2021"
    Description        = "Create PSDrives of common cloud storage providers."
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    # FunctionsToExport  = "*"

    # CmdletsToExport    = @()

    # VariablesToExport  = "*"

    # AliasesToExport    = "*"

    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()

    PrivateData        = @{

        PSData = @{

            # Tags = @()

            # LicenseUri = ""

            # ProjectUri = ""

            # IconUri = ''

            # ReleaseNotes = ''

            # Prerelease = ""

            # RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}